name: CI

on:
  push:
    branches: ['main']
  pull_request:
  schedule:
    - cron: "32 4 * * 5"

jobs:
  Package:
    strategy:
      matrix:
        package: [
          askama, askama_derive, askama_escape,
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          key: ${{ matrix.package }}
          components: clippy
      - run: cd ${{ matrix.package }} && cargo clippy --all-targets -- -D warnings

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          key: lint
          components: rustfmt, clippy
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
